"""Initial migration

Revision ID: ae86d28dc9f6
Revises: 
Create Date: 2025-11-23 15:21:30.679887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae86d28dc9f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('tle_line1', sa.String(), nullable=False),
    sa.Column('tle_line2', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellites_category'), 'satellites', ['category'], unique=False)
    op.create_index(op.f('ix_satellites_id'), 'satellites', ['id'], unique=False)
    op.create_index(op.f('ix_satellites_name'), 'satellites', ['name'], unique=False)
    op.create_index(op.f('ix_satellites_norad_id'), 'satellites', ['norad_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('supabase_id', sa.String(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'satellite_id', name='unique_user_satellite')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('min_elevation', sa.Float(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'satellite_id', name='unique_user_satellite_notification')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('pass_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('aos_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('los_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_elevation', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pass_predictions_aos_time'), 'pass_predictions', ['aos_time'], unique=False)
    op.create_index(op.f('ix_pass_predictions_id'), 'pass_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_pass_predictions_quality_score'), 'pass_predictions', ['quality_score'], unique=False)
    op.create_index(op.f('ix_pass_predictions_satellite_id'), 'pass_predictions', ['satellite_id'], unique=False)
    op.create_index(op.f('ix_pass_predictions_user_id'), 'pass_predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pass_predictions_user_id'), table_name='pass_predictions')
    op.drop_index(op.f('ix_pass_predictions_satellite_id'), table_name='pass_predictions')
    op.drop_index(op.f('ix_pass_predictions_quality_score'), table_name='pass_predictions')
    op.drop_index(op.f('ix_pass_predictions_id'), table_name='pass_predictions')
    op.drop_index(op.f('ix_pass_predictions_aos_time'), table_name='pass_predictions')
    op.drop_table('pass_predictions')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_satellites_norad_id'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_name'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_id'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_category'), table_name='satellites')
    op.drop_table('satellites')
    # ### end Alembic commands ###
